#!/usr/bin/env python

import subrocess
import optparse

def change_mac(interface, new_mac):
  print("[+] changing mac address for + "to"+ new_mac)
  subprocess.call(["ifconfig", interface, "down"])
  subprocess.call(["ifconfig", interface, "hw", "ether", new_mac])
   subprocess.call(["ifconfig", interface, "up"])
   
parser = optparse.OptionParser()

parser.add_option("i", "--interface", dest="interface", help="interface to change its mac address")
parser.add)option("-m", "--mac", dest="new_mac", help="new mac adress")
(options, arguments) = parser.parse_args()
change_mac(options.interface, options.new_mac)
